### ISSUE TITLE
Writing Vectors to Postgres

### ISSUE THREAD

**Issue by cbeav** [tathougies/beam#351]
Got a column on a PG table with type `Columnar f (Vector Int)`. I can read from this no problem, but when I attempt to construct an expression to insert via `runInsertReturningList`, I see the following:

```
No instance for (Database.Beam.Backend.SQL.SQL92.HasSqlValueSyntax
                         Database.Beam.Postgres.Syntax.PgValueSyntax (Vector Int))
```

I saw a couple potentially related issues fixed both prior to and after the most recent release, but am able to reproduce this on `master` as well as `0.3.2.2`.

It is my understanding the instance for this should exist (See #314). Is there something I'm failing to understand about pg array support here?

**Comment by cbeav** [comment]
Ugh, my b, my b. Was not building `beam-postgres` from master. Anyone else who comes across this, here's my funky fresh `stack.yaml`:

```
resolver: lts-12.13

packages:
- .

extra-deps:
- git: https://github.com/tathougies/beam
  commit: dccbb4a897536ed7595f6d64fa568053a0d34c86
  subdirs:
  - beam-core
  - beam-postgres
```
