### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by 3noch** [tathougies/beam#47]
:D

This also will get the project into `nixpkgs.haskellPackages` without being manually added.

**Comment by 3noch** [comment]
This library looks amazing.

**Comment by tathougies** [comment]
Thanks! I have a few things I'd like to add to beam-migrate, but sure, then i'm planning on a full release :)

**Comment by 3noch** [comment]
@tathougies Oh wow I didn't realize that it's been almost 2 years since a hackage release. Is it safe to use this from `master` branch?

**Comment by tathougies** [comment]
Yes, safe to use from master branch, but there are several changes compared to hackage (and a version bump to go along). I would recommend going over the [new docs](https://tathougies.github.io/beam/) to stay up-to-date.

**Comment by 3noch** [comment]
@tathougies Thanks. That's actually what I've been reading and they're very well done. That's why I was so surprised to find Hackage out-of-date. Most packages never get around to docs, but you've done them even prior to release!

**Comment by tathougies** [comment]
@3noch We use it at work, so my colleagues need docs :) Feel free to join the mailing list and IRC channel if you have questions.

**Comment by reygoch** [comment]
@tathougies I'm a bit confused, documentation says we can install beam from stack but stack has no memory of beam :)

Was it removed from current lts?

**Comment by csi-adziahel** [comment]
> stack has no memory of beam :)

That seems to work for me:

```yaml
packages:
- .
- location:
    git: 'https://github.com/tathougies/beam.git'
    commit: 'abe473a'
  extra-dep: true
  subdirs:
  - beam-core
  - beam-migrate
  - beam-sqlite
```
